name: deploy
on:
  push:
    branches:
      - master
jobs:
  cloudformation:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: credential
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: deploy
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: twishlist
          template: template.yml
          no-fail-on-empty-changeset: 1
